package krcho.gui;

import java.awt.Color;

/**
 * Game setting dialog, using own created javaBean, for set up cardTypes
 * and backgroundTypes
 *
 * @author Jozef Krcho
 */
public class JDialogSettings extends javax.swing.JDialog {

    private boolean isCancel;

    public JDialogSettings(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        isCancel = false;

        cardTypes.addUnit("/obrazky/karty1unselect.png", "/obrazky/karty1select.png", "Clasic", "/obrazky/karty1.png");
        cardTypes.addUnit("/obrazky/karty2unselect.png", "/obrazky/karty2select.png", "Royal", "/obrazky/karty2.png");
        cardTypes.setImgXSize(86);
        cardTypes.setImgYSize(131);

        backgroundTypes.addUnit("/obrazky/zelenaUnselect.png", "/obrazky/zelenaSelect.png", "Zelena", new Color(153, 255, 153));
        backgroundTypes.addUnit("/obrazky/zltaUnselect.png", "/obrazky/zltaSelect.png", "Zlta", new Color(255, 255, 153));
        backgroundTypes.addUnit("/obrazky/cervenaUnselect.png", "/obrazky/cervenaSelect.png", "Cervena", new Color(255, 153, 153));
        backgroundTypes.setImgXSize(86);
        backgroundTypes.setImgYSize(87);

        repaint();
    }

    /**
     * get selected background color.
     *
     * @return color
     */
    public Color getBackgroundColor() {
        return (Color) backgroundTypes.getChoosedData();
    }

    /**
     * get selected card type
     *
     * @return String path to cards png
     */
    public String getCardType() {
        return (String) cardTypes.getChoosedData();
    }

    public boolean getJeZrusene() {
        return isCancel;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardTypes = new javabeanschooser.TypeChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backgroundTypes = new javabeanschooser.TypeChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout cardTypesLayout = new javax.swing.GroupLayout(cardTypes);
        cardTypes.setLayout(cardTypesLayout);
        cardTypesLayout.setHorizontalGroup(
            cardTypesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        cardTypesLayout.setVerticalGroup(
            cardTypesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );

        jLabel1.setText("Typ Kariet:");

        jLabel2.setText("Typ Pozadia:");

        javax.swing.GroupLayout backgroundTypesLayout = new javax.swing.GroupLayout(backgroundTypes);
        backgroundTypes.setLayout(backgroundTypesLayout);
        backgroundTypesLayout.setHorizontalGroup(
            backgroundTypesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        backgroundTypesLayout.setVerticalGroup(
            backgroundTypesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );

        jButton1.setText("Zrušiť");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Uložiť");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardTypes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backgroundTypes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 450, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backgroundTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Set up field, that you want to save changes and close dialog.
     *
     * @param evt
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        isCancel = false;
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Set up field, that you don't want to save changes and close dialog.
     *
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        isCancel = true;
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javabeanschooser.TypeChooser backgroundTypes;
    private javabeanschooser.TypeChooser cardTypes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
